version: '3.8'

services:
  portfolio-app:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development service (uncomment to use)
  # portfolio-dev:
  #   build: .
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm start
  #   restart: unless-stopped
